on:
  push:
    branches:
      - main
jobs:
  env_vars:
    runs-on: ubuntu-latest
    outputs:
      SAFE_WEB_CORE_VERSION: ${{ steps.env-file.outputs.SAFE_WEB_CORE_VERSION }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Use env file
        id: env-file
        run: grep -v '#' .env | tee $GITHUB_OUTPUT
        
  version_outputs:
    runs-on: ubuntu-latest
    needs: env_vars
    steps:
      - uses: actions/checkout@v3
      
      - name: Output safe-global/web-core version
        run: echo ${{ needs.env_vars.outputs.SAFE_WEB_CORE_VERSION }}
        
  checkout:
    runs-on: ubuntu-latest
    needs: env_vars
    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout safe-global/web-core repo tag ${{ needs.env_vars.outputs.SAFE_WEB_CORE_VERSION }}
        uses: actions/checkout@v3
        with:
          repository: safe-global/web-core
          path: web-core
          ref: ${{ needs.env_vars.outputs.SAFE_WEB_CORE_VERSION }}
          
      - name: Update Dockerfile
        run: cp Dockerfile ./web-core/Dockerfile
        
      - name: Output Dockerfile
        run: cat /web-core/Dockerfile
      
      - name: Set Docker Tag
        run: echo "DOCKER_TAG=${{ needs.env_vars.outputs.SAFE_WEB_CORE_VERSION }}-${GITHUB_SHA:0:7}-$(date +%s)" | tee $GITHUB_ENV

#       - name: Login to Docker Repository
#         uses: docker/login-action@v2
#         with:
#           registry: core-harbor.us-east-2.codefi.network
#           username: ${{ secrets.DOCKER_REPO_USER }}
#           password: ${{ secrets.DOCKER_REPO_TOKEN }}

#       - name: Docker Build and Push
#         id: docker-build
#         uses: docker/build-push-action@v4
#         with:
#           push: false
#           tags: core-harbor.us-east-2.codefi.network/palm/palm-bridge-ui:${{ env.DOCKER_TAG }}
